### ISSUE TITLE
Source must be specified. See generator/sources directory.

### ISSUE THREAD

**Issue by thomas992** [rionlabs/kanji.sh#402]
**Describe the bug**
I am unable to specify a source

**To Reproduce**
node main.js jlpt n1

**Expected behavior**
Generates JLPT worksheets

**Additional context**
I am using my own fork that I made that helped getting it working

**Comment by thomas992** [comment]
```PS C:\Users\tomha\Documents\GitHub\kanji.sh\generator> node main.js
[START] Downloading Kanji data
[DONE✓] Kanji data already downloaded
[START] File sources\jlpt\n1.source for jlpt
C:\Users\tomha\Documents\GitHub\kanji.sh\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:236
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

&page=33&title=JLPT N1OT_FOUND at file:///Users\tomha\Documents\GitHub\kanji.sh\generator\template\page.html?data=孤
    at navigate (C:\Users\tomha\Documents\GitHub\kanji.sh\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:236:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (C:\Users\tomha\Documents\GitHub\kanji.sh\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Frame.js:206:21)
    at async CDPPage.goto (C:\Users\tomha\Documents\GitHub\kanji.sh\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:439:16)
    at async processing (C:\Users\tomha\Documents\GitHub\kanji.sh\generator\main.js:99:17)
    at async run (C:\Users\tomha\Documents\GitHub\kanji.sh\node_modules\p-queue\dist\index.js:163:29)
```
Changing it to "jlpt" manually in the code leads to this error I am not sure how to fix.

**Comment by thomas992** [comment]
At line 100 of main.js I added C:/ to the line and it fixed it but I have another issue.
````file:///C:/${config.templateAbsolutePath}?data=${kanjiArray.join('')}&page=${```
![Screenshot 2023-07-19 154924](https://github.com/rionlabs/kanji.sh/assets/31554741/9e605953-ae55-4c00-9846-a407843e8915)
After the pages generate they all get deleted and replaced with a 1kb file meant to be the unit.
The kanji does not pop up before they are deleted but all the pages get generated

**Comment by thomas992** [comment]
I fixed it on my fork
